### PR TITLE
Avoid errors with STATE variables without DERIVATE block

### PR DESCRIPTION
**Pull request by pramodk**
* In case of state variables without ODEs or  SOLVE block we get
   errors like:

   V not really a STATE; Ie. No differential equation for it
   gNMDA not really a STATE; Ie. No differential equation for it

 * Not sure about the "desirable" fix here:

   - should we avoid declaring variables as STATE
   - use workaround of empty SOLVE block like this PR
   - have fix in neuron to avoid this as an error

Tagging @nrnhines for this to discuss.

### CODE REVIEW

**Comment by nrnhines** [comment]
I'm looking into this. I see that the error occurs with ```NEURON -- VERSION 7.6.7 HEAD (603da174f) 2019-04-19```. Also, the now deprecated http://github.com/nrnhines/nrnverify_modeldb never attempted to run this model. That error message has been present since before 2007 ```[svn r1897] start development of 6.2``` which is as old as the git repository goes.

**Comment by pramodk** [comment]
Ok, thanks michael for checking.

May be I can remove mentioned variables as `STATE` and turn them into `ASSIGN`? that might be simpler than empty `SOLVE` block?

**Comment by nrnhines** [comment]
I emailed Salvadore. I'm guessing the wrong version of izhi2007.mod inadvertently ended up in the submitted modeldb zip file.

**Comment by pramodk** [comment]
Ok. For now, I have converted STATE variables to ASSIGN. Let's see what @salvadord says.

**Comment by olupton** [comment]
@pramodk this PR also needs an entry in the README

**Comment by pramodk** [comment]
Done!

**Comment by pramodk** [comment]
> I emailed Salvadore. I'm guessing the wrong version of izhi2007.mod inadvertently ended up in the submitted modeldb zip file.

@nrnhines / @salvadord: was there any conclusion on the above? Otherwise, a simple/compatible change with neuron is to just to not have `STATE` variables but `ASSIGNED`. Let us know how to proceed here.

**Comment by nrnhines** [comment]
@pramodk I think changing to ASSIGNED is the best way to proceed.

**Comment by salvadord** [comment]
@nrnhines @pramodk Sorry for the late reply. Changing to ASSIGNED makes sense. In a later version of this izhikevich mod file we had actually made that change already, see here: https://senselab.med.yale.edu/ModelDB/ShowModel?model=39948&file=/izhikevich_simple_nrn/izhi2007a.mod#tabs-2

**Comment by pramodk** [comment]
thank you for confirming @salvadord !

**Pull request merged**
